### PR TITLE
Fix 'styled system' table in Readme

### PR DESCRIPTION
**Pull request by dimitrisnl**
Connects-To: #487
Change-Type: patch
---- Autogenerated Waffleboard Connection: Connects to #487

### CODE REVIEW

**Comment by dimitrisnl** [comment]
https://github.com/resin-io-modules/rendition/pull/488/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by dimitrisnl** [comment]
@LucianBuzzo The tests fail for some reason https://travis-ci.org/resin-io-modules/rendition/builds/397329601?utm_source=github_status&utm_medium=notification

Can I just skip it with`versionbot/no-checks`?

**Comment by LucianBuzzo** [comment]
@thgreasi I just tried re running the build and it passed

**Comment by dimitrisnl** [comment]
Strangely it failed twice for me

**Pull request merged**
