### PR TITLE
configuration: Use the recommended approach for storybook actions

### PR DESCRIPTION
**Pull request by dimitrisnl**
Connects-to: #545 
Change-type: patch
Signed-off-by: Dimitrios Lytras <dimitrios@resin.io>
---- Autogenerated Waffleboard Connection: Connects to #545

### CODE REVIEW

**Comment by dimitrisnl** [comment]
The installed package has already been registered in the `.storybook/addons` as seen [here](https://github.com/resin-io-modules/rendition/blob/master/.storybook/addons.js#L2)

**Comment by LucianBuzzo** [comment]
@dimitrisnl Is this connects-to correct? It links to a seemingly unrelated PR. Also, could you clarify what the "recommended approach" is? Is this recommended by the storybook authors, or someone else?

**Comment by dimitrisnl** [comment]
@LucianBuzzo Apologies for the issue type will fix that soonish.

The 'recommended' (for the lack of a better word) approach is the one outlined in the storybook docs and linked in the deprecation notice https://github.com/storybooks/storybook/tree/master/addons/actions

**Comment by LucianBuzzo** [comment]
@dimitrisnl Thanks for clarifying!

**Pull request merged**
