### PR TITLE
Limit DropDownButton's length

### PR DESCRIPTION
**Pull request by dimitrisnl**
Connects-To: #410
Change-Type: patch
---- Autogenerated Waffleboard Connection: Connects to #410

### CODE REVIEW

**Comment by dimitrisnl** [comment]
Just noticed that the updated snapshot belongs to `NavBar`

**Comment by LucianBuzzo** [comment]
@dimitrisnl  Oh thats weird, yeah, discard it please

**Comment by dimitrisnl** [comment]
@LucianBuzzo The thing is that every time I run `jest --updateSnapshot` I get the same changes. 

Could you confirm it if you have some spare time?

**Comment by LucianBuzzo** [comment]
@dimitrisnl I can't replicate the issue you're seeing, perhaps you need to run `rm -rf node_modules && npm install`? In the meantime I'm happy to merge this PR.

**Pull request merged**
