### PR TITLE
Modal: make action prop optional and default to 'Ok'

### LINKED ISSUE #330: Modal: Add default for 'action' prop

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Fixes #330

change-type: minor

### CODE REVIEW

**Comment by LucianBuzzo** [comment]
@thgreasi The styleguide just shows the text `Main CTA`. We typically use sentence case for CTA text, and I think 'Ok' is a generic enough confirmation word to use here.

screen shot 2018-01-26 at 16 30 07

**Comment by thgreasi** [comment]
@LucianBuzzo totally agree about using ok, I was just wondering how the sentence case of acronyms like ok should be  :)

**Comment by LucianBuzzo** [comment]
@thgreasi Figuring out the 'proper' way to write ok turns out to be a bit of a minefield
- http://www.writing-skills.com/ok-ok-okay-how-do-you-write-ok
- https://en.wikipedia.org/wiki/OK
- https://english.stackexchange.com/questions/108213/must-ok-only-be-written-in-capital-letters

@sonyagreen @zwalchuk You guys might be able to give us some useful info, how should we display the work 'OK' on the modal confirmation?

**Comment by sonyagreen** [comment]
Oooh, good resin style guide question. As much as I love a good grammatical issue, I think this is more about the look and feel of our product, and what's most universal.
* is "OK" the word we want? Would we consider something a bit more cheeky like "Got it!" 
* is there an industry standard for this?

**Comment by zwalchuk** [comment]
I don't think I'm qualified to comment on the appropriate amount of cheekiness for a button, but if we do stick with OK I think it should definitely be all capital.

**Comment by LucianBuzzo** [comment]
Thanks for the feedback @zwalchuk @sonyagreen 
I think we should go with "OK" for the CTA text.

**Pull request merged**
