### PR TITLE
Change Progress Bar background

### PR DESCRIPTION
**Pull request by amdomanska**
from gray.light to quartenary.main
Change-type: patch
Signed-off-by: amdomanska <aga@resin.io>
connects-to: #537

image

### CODE REVIEW

**Comment by amdomanska** [comment]
I can't see what is wrong with my commit...

**Comment by dimitrisnl** [comment]
@amdomanska The structure for the commit is as follows

[prefix]: [Commit Body]

Connects-to: #
Change-type: 
Signed-off-by:

So I assume that 
a) There is a missing newline above 'Connects-to'
b) There is no prefix present (this could be optional in this repo though)

**Comment by amdomanska** [comment]
@dimitrisnl what is prefix? Is it #570 in this case?

**Comment by LucianBuzzo** [comment]
@amdomanska prefix usually indicates what part of the project you are changing, something like:
```
ProgressBar: Change background color
```
Would be fine

**Comment by amdomanska** [comment]
@resin-ci retest

**Pull request merged**
